### ISSUE TITLE
Question/Feature: Is it possible to add the varying examples/n from the datasets?

### ISSUE THREAD

**Issue by kishanpb** [st-tech/zr-obp#124]
The papers you cited (like Su+ 20, Wang+ 17, Dudik+ 14) all vary the number of examples and repeat the OPE experiments. I am referring to Figure (2a) from Wang+ 17:

![Figure 2a](https://user-images.githubusercontent.com/9605238/131284383-a7a6791f-4e33-4ac5-88f9-c0bcfc0d523e.png)

Any pointers on how do I go about doing this efficiently in this repo are appreciated!

**Comment by usaito** [comment]
Hi Kishan! Thank you for interest.

I once implemented that kind of simulation with synthetic data. You can refer to this.

https://colab.research.google.com/drive/1_-kKolkqp5SgwOPKenxgssBMkFrfqEAQ?usp=sharing

Please don't hesitate to reach out, when you have questions! Some package updates will also come soon...
