### ISSUE TITLE
typo in quickstart

### ISSUE THREAD

**Issue by nmasahiro** [st-tech/zr-obp#13]
https://github.com/st-tech/zr-obp/blob/master/examples/quickstart/quickstart.ipynb

Since the difference cannot be seen clearly in jupyter notebook, I created this issue instead of a pull request.

(2) Offline Bandit Simulation
We use Bernoulli TS impelemted in => implemented

(3) Off-Policy Evaluation (OPE)
estimatorsand estiamte => estimators and estimate

In addition to the above, I think it is better to unify the following two expressions:
* (2) Off-Policy Learning
* (2) Offline Bandit Simulation

**Comment by usaito** [comment]
@nmasahiro 

Thanks! I fixed the raised typos in some of my previous PRs.

> In addition to the above, I think it is better to unify the following two expressions:

Yeah, it is a great idea, and I decided to use "off-policy learning" instead of "offline bandit simulation" for whole contents: https://github.com/st-tech/zr-obp/pull/17
