### ISSUE TITLE
Switch DR current estimator has a typo 

### ISSUE THREAD

**Issue by kishanpb** [st-tech/zr-obp#136]
Switch DR equation from 17-Wang-Agarwal-Dudik is 
<img width="318" alt="Screen Shot 2021-09-15 at 3 52 54 PM" src="https://user-images.githubusercontent.com/9605238/133508071-81cbe7f4-278e-4af5-8520-e97294516c4e.png">

The current implementation does this:
<img width="1102" alt="Screen Shot 2021-09-15 at 3 52 30 PM" src="https://user-images.githubusercontent.com/9605238/133508149-0568a38c-406c-4d6d-a0bb-ef5d3d2f2f72.png">

This should fix it:
```
        estimated_rewards = np.average(
            q_hat_at_position,
            weights=pi_e_at_position * switch_indicator_xt_all_actions,
            axis=1,
        )
        estimated_rewards += switch_indicator * iw * reward
        return estimated_rewards
```

Although I am not sure how to calculate `switch_indicator_xt_all_actions` since `pscore` for all actions isn't available. Thanks! :)

**Comment by usaito** [comment]
@kishanpb 

Thank you for your question! Eq (7) is what we call Switch-IPS, and it is a bit difficult to implement... 

Switch Doubly Robust is a different one, which combines DM and DR, not DM and IPS. You can find the following statement right after Eq. (7).

> When DR is used instead of IPS, we refer to the resulting estimator as SWITCH-DR.

**Comment by kishanpb** [comment]
Oh, sorry, I missed that statement! Thanks!

But, won't we need an indicator for the DM term? Currently, whenever `w\leq\lambda`, it is choosing both DM and DR.

Can we get `\pi_e(x,a)` and `\pi_b(x,a)` for all contexts and actions in the estimators classes? That'd be useful for Switch-IPS.

**Comment by usaito** [comment]
@kishanpb 

DR itself has a DM part, so I think the indicator of the DM part will disappear in the end. Please let me know if I misunderstand something here..

<img width="899" alt="スクリーンショット 2021-09-15 19 26 16" src="https://user-images.githubusercontent.com/32621707/133537086-6886c252-5efe-491b-b200-f570cd1527f6.png">


> Can we get \pi_e(x,a) and \pi_b(x,a) for all contexts and actions in the estimators classes? That'd be useful for Switch-IPS.

We can get \pi_e(x,a) for all (realized) context-action pairs (action_dist), but it is not the case for \pi_b(x,a). From a practical perspective, it is not that realistic to log all possible \pi_b(x,a) in the bandit feedback. This is, I think, one of the drawbacks of Switch-IPS.

**Comment by kishanpb** [comment]
Oh, this is neat! Thank you very much!

One can send both \pi_e and \pi_b from `obtain_batch_bandit_feedback` module, no? Please remind me why one can't log all \pi_b's?

**Comment by usaito** [comment]
It is not impossible, so if you want, you may be able to do in your practice. However, for example, in recommender system applications, there will be millions of actions, making it nearly impossible to completely log \pi_b.  Moreover, the other estimators are usable with only \pi_b(a_i|x_i), so there is not a big incentive to log \pi_b.

It is not also impossible to make modifications to, for example, `obp.dataset.SyntheticBanditDataset`, to output \pi_b for all possible actions, but it will limit the scalability of the function, so we have to consider how to make modifications carefully...
