### ISSUE TITLE
Question: Can we select different regression models for different estimators?

### ISSUE THREAD

**Issue by kishanpb** [st-tech/zr-obp#137]
In the [multiclass](https://github.com/st-tech/zr-obp/tree/master/examples/multiclass) example, `\hat{q}` is the same for all OPE estimators. Is it possible to use different `\hat{q}` estimators for different OPE estimators? Specifically, I wanted to also add MRDR in this multiclass example, but I couldn't since the regression_model is shared by all OPE estimators.
Thanks in advance for any help! :)

**Comment by usaito** [comment]
@kishanpb Great question! You can use a dictionary to do that, e.g.,

```python
ope.estimate_policy_value(
    action_dist=action_dist,
    estimated_rewards_by_reg_model={
        "dr": q_hat_1,
        "mrdr": q_hat_2,
    }
)
```

this should work..

**Comment by kishanpb** [comment]
Quick question: Here ```{
        "dr": q_hat_1,
        "mrdr": q_hat_2,
        ...
    } ```
`"dr"` is the given estimator_name and `q_hat_1` is the q_hat_estimate from the regression model right?

**Comment by usaito** [comment]
Yes, exactly
