### ISSUE TITLE
Question: What is the source of the construction of evaluation and behavior policies?

### ISSUE THREAD

**Issue by kishanpb** [st-tech/zr-obp#139]
Hi zr-obp team.

In the multiclass.py I see evaluation and behavior policies are as follows:
```
# construct an evaluation policy
        pi_e = np.zeros((self.n_rounds_ev, self.n_actions))
        pi_e[:, :] = (1.0 - alpha_e) / self.n_actions
        pi_e[np.arange(self.n_rounds_ev), preds] = (
            alpha_e + (1.0 - alpha_e) / self.n_actions
        )
# construct a behavior policy
        pi_b = np.zeros((self.n_rounds_ev, self.n_actions))
        pi_b[:, :] = (1.0 - self.alpha_b) / self.n_actions
        pi_b[np.arange(self.n_rounds_ev), preds] = (
            self.alpha_b + (1.0 - self.alpha_b) / self.n_actions
        )
```
Which paper does this follow from? 

Also, have you tried the following from 20-Su+ paper?
<img width="443" alt="Screen Shot 2021-09-23 at 11 09 50 PM" src="https://user-images.githubusercontent.com/9605238/134617552-78bf705d-ac44-442a-a1d6-dd0f38c14bec.png">

Thanks!

**Comment by usaito** [comment]
@kishanpb Our implementation corresponds to the case with \beta = 0 in your picture (i.e., Su et al. 2020). You can choose \alpha to produce evaluation and behavior policies (alpha_e / alpha_b).
