### ISSUE TITLE
Loading my own data?

### ISSUE THREAD

**Issue by misterwindupbird** [st-tech/zr-obp#147]
I have my own log data which I would like to run OPE on. Is this supported? I don't see any way of bringing it into a `odp.dataset`.

**Comment by usaito** [comment]
If you'd like to use your own data, it may be useful to define a new class specific to the dataset, like we do in [`obp.dataset.OpenBanditPipeline`](https://github.com/st-tech/zr-obp/blob/master/obp/dataset/real.py). Then, you can incorporate your own preprocessing such as feature engineering. 

Or, more simply, you can just use the raw context, action, reward, and pscore (propensity score), recorded in your dataset and feed them into the estimators implemented in `obp.ope` (without defining any new dataset class). It may be good to refer to some examples (like [this](https://github.com/st-tech/zr-obp/blob/master/examples/quickstart/synthetic.ipynb)), and replace the inputs (`context`, `action`, `reward`, `pscore`, etc) with yours to run OPL or OPE.


(Does the above explanation make sense? I'm happy to address some additional questions.)

**Comment by misterwindupbird** [comment]
Thank you! I was about to write my own subclass already as per your first suggestion, just wanted to make sure I was on the right track.

Slightly off-topic, and apologies if this is documented somewhere, but what are the requirements of the context vectors when the context is categorical? Does it need to be a metric space? In my situation, the only context is a userID, a siteID, and an entry point (home page vs a dedicated recommendations page), would it be better to use provide raw values, indices, do a one-hot, or try an embedding, etc?

**Comment by usaito** [comment]
> Thank you! I was about to write my own subclass already as per your first suggestion, just wanted to make sure I was on the right track.

Great!

> but what are the requirements of the context vectors when the context is categorical?

I think this is totally dependent on the dataset you use, as in the supervised ML. I mean, one-hot encoding might be enough or a good embedding might gives you a huge improvement. One-hot encoding would be a good starting point, and you can validate what kind of feature engineering is good for policy learning via off-policy evaluation (data-driven way).
