### ISSUE TITLE
contents of "item_context.csv" in OBD are different for random policy and Bernoulli TS policy

### ISSUE THREAD

**Issue by haanvid** [st-tech/zr-obp#162]
I downloaded OBD from https://research.zozo.com/data.html#OpenBanditDataset

I checked item_context.csv in both "open_bandit_dataset/bts/all/item_context.csv" and "open_bandit_dataset/random/all/item_context.csv" and found that both of them contain same values for the item_feature_0. But different values for rest of the item_features or columns in the file (item_feature_1, item_feature_2, item_feature_3)
         
why are they differnt while they should be same since they describe same 80 items (or actions for the bandit) do they use different values to describe a same feature?

**Comment by usaito** [comment]
I think this is the same question: https://github.com/st-tech/zr-obp/issues/163

**Comment by haanvid** [comment]
ok, thanks
