### ISSUE TITLE
"action_context" arrays in bandit feedbacks of different policies have different values

### ISSUE THREAD

**Issue by haanvid** [st-tech/zr-obp#163]
I checked "action_context" arrays in both bandit_feedbacks acquired with random and Bernoulli TS policies and they are different. Why are they different?
          Do they use different values to describe a same feature except the last column which are filled with real values?
          below is the code that I ran to check:

	###############################################################################
	from obp.dataset import OpenBanditDataset

	dataset_random = OpenBanditDataset(behavior_policy="random", campaign="all")
	dataset_bts = OpenBanditDataset(behavior_policy="bts",    campaign="all")
	bandit_feedback_random = dataset_random.obtain_batch_bandit_feedback()
	bandit_feedback_bts = dataset_bts.obtain_batch_bandit_feedback()

	np.sum(np.abs(bandit_feedback_random['action_context'] - bandit_feedback_bts['action_context']))  # they don't give zero
	>> 1143.0
	##############################################################################

**Comment by usaito** [comment]
item_feature_1 ~ item_feature_3 are categorical features. So, the recorded/encoded values do not have any meaning. If you compare "action_context" under bts/random, you'll realize that both action_contexts are "categorized" in the same way. If you want to learn a classifier that can generalize across different datasets wrt the action context for some reason, please implement your own feature preprocessing or just use one of the action_context.

**Comment by haanvid** [comment]
thanks for the reply
