### ISSUE TITLE
"action_context" arrays in bandit feedbacks & item_context.csv (downloaded from https://research.zozo.com/data.html#OpenBanditDataset)

### ISSUE THREAD

**Issue by haanvid** [st-tech/zr-obp#164]
In my under standing, both "action_context" and item_context.csv represents each action (total 80 actions) in 4 dimensional vectors. (80 actions, 4 dimensional vectors to describe each of them => (80,4) array)

But it seems that the action_context and item_context.csv have different values. Why is it so?

The first column (real values) of item_context.csv seems to match the last column of action_context

2nd to 4th columns of item_context.csv seems to be in 1st to 3rd columns of action_context with different values assigned to describe a same feature of an item (or action)

By "action_context" I mean   bandit_feedback_random['action_context'],  bandit_feedback_bts['action_context'] from below

```
###############################################################################
from obp.dataset import OpenBanditDataset

dataset_random = OpenBanditDataset(behavior_policy="random", campaign="all")
dataset_bts = OpenBanditDataset(behavior_policy="bts",    campaign="all")
bandit_feedback_random = dataset_random.obtain_batch_bandit_feedback()
bandit_feedback_bts = dataset_bts.obtain_batch_bandit_feedback()
 
np.sum(np.abs(bandit_feedback_random['action_context'] - bandit_feedback_bts['action_context'])) # they don't give 0
#   returns : 1143.0
##############################################################################
```

**Comment by usaito** [comment]
> In my under standing, both "action_context" and item_context.csv represents each action (total 80 actions) in 4 dimensional vectors. (80 actions, 4 dimensional vectors to describe each of them => (80,4) array)

this is correct

> But it seems that the action_context and item_context.csv have different values. Why is it so?

item_feature_1 ~ item_feature_3 are categorical features. So, the recorded/encoded values do not have any meaning. If you compare "action_context" under bts/random, you'll realize that both action_contexts are "categorized" in the same way.

**Comment by haanvid** [comment]
OK, thanks! 
I just checked that they are just categorized in a same way. 

This would mean that I may just use one of the 4 choices of [4 dimensional vector representation for 80 actions]?
The four choices mentioned would be : 1. action context  from Bernoulli TS, 2. action context  from random policy, 3. item_context.csv from Bernoulli TS, 4. item_context.csv from random policy

**Comment by haanvid** [comment]
I think the "action_context" in the newer version of obp contains additional one redundant categorical dimension  dimension (now the shape of the action_context is not 80x4 but 80x5) which has 80 kinds of categorical values while the action is 80.
