### ISSUE TITLE
Could I get to know what each dimension in item_context.csv or "action_context" array from bandit feedback  are representing?

### ISSUE THREAD

**Issue by haanvid** [st-tech/zr-obp#165]
Could I get to know what each dimension in item_context.csv or "action_context" array from bandit feedback  are representing?

I looked for description in the documentation but I was unable to find the description

**Comment by usaito** [comment]
No, we can't disclose what each dimension means. Sorry for that.

**Comment by haanvid** [comment]
OK, thanks for the reply
