### ISSUE TITLE
How to use kernelized inverse probability weighting with OBD and OBP

### ISSUE THREAD

**Issue by haanvid** [st-tech/zr-obp#166]
In the appendix of the paper (https://arxiv.org/pdf/2008.07146.pdf) introducing OBD and OBP, it is mentioned in Appendix E.1 that the kernelized inverse probability weighting [Kallus et al., 2018] is implemented on the Open Bandit Pipeline.
 
How is the algorithm used in OBP with OBD containing discrete actions? 
Do you use the real values contained in the first dimension of item_context.csv? 

referenced paper:
[Kallus et al., 2018] Nathan Kallus and Angela Zhou. Policy evaluation and optimization with continuous treatments. AISTATS 2018.

**Comment by usaito** [comment]
Hi,

"kernelized inverse probability weighting" is for continuous actions, so it is irrelevant to OBD, which is a discrete action dataset

**Comment by haanvid** [comment]
Thanks for the reply.
