### ISSUE TITLE
Quickstart is not working without preparing obd directory

### ISSUE THREAD

**Issue by nmasahiro** [st-tech/zr-obp#27]
If we only installed obp with pip, the current [Quickstart](https://zr-obp.readthedocs.io/en/latest/quickstart.html) raises the following error:

```
>>> from obp.dataset import OpenBanditDataset
>>> from obp.policy import BernoulliTS
>>> from obp.ope import OffPolicyEvaluation, InverseProbabilityWeighting as IPW
>>> dataset = OpenBanditDataset(behavior_policy='random', campaign='all')

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-b5fa4ef965ba> in <module>
----> 1 dataset = OpenBanditDataset(behavior_policy='random', campaign='all')

~~~

FileNotFoundError: [Errno 2] No such file or directory: 'obd/random/all/all.csv'
```

​I understand that the `obd` directory should be prepared in advance (e.g., cloning this repository); however, the current [Quickstart](https://zr-obp.readthedocs.io/en/latest/quickstart.html) page does not provide such descriptions, which may confuse the users a little.
Therefore, I think it's a good idea to add such a note to the page.

I'm sorry if I misunderstood.

**Comment by usaito** [comment]
Thanks! Can you fix this issue?

**Comment by nmasahiro** [comment]
Sure! I will create a PR later.
