### ISSUE TITLE
`obp.dataset.BaseBanditDataset` class does not exist

### ISSUE THREAD

**Issue by fullflu** [st-tech/zr-obp#29]
Reading the `(1) Data loading and preprocessing` section of `./README.md`,  the following sentence gives me the impression that `obp.dataset.BaseBanditDataset` class exists.

> Moreover, by following the interface of `obp.dataset.BaseBanditDataset` class, one can handle future open datasets for bandit algorithms other than our Open Bandit Dataset. dataset module also provide a class to generate synthetic bandit datasets.

In the `obp.dataset.base.py`, however, only `BaseRealBanditDataset` and `BaseSyntheticBanditDataset`classes  are defined.

Are you planning to implement `obp.dataset.BaseBanditDataset` class?
If not, I propose  that **`obp.dataset.BaseBanditDataset`** be replaced with **`obp.dataset.BaseRealBanditDataset` or `obp.dataset.BaseSyntheticBanditDataset`**  in the `./README.md`.

**Comment by usaito** [comment]
Thanks! Yeah, `obp.dataset.BaseRealBanditDataset` is correct here. Can you fix this later, along with some potential minor errors?

**Comment by fullflu** [comment]
Yes, I’ll do it!

**Comment by usaito** [comment]
The (1) Data loading and preprocessing section disappeared from the main README...
https://github.com/st-tech/zr-obp/pull/50
