### ISSUE TITLE
Citation format lacks uniformity

### ISSUE THREAD

**Issue by fullflu** [st-tech/zr-obp#30]
## README.md and README_JN.md
 
1.  author={Saito, Yuta and Shunsuke Aihara and Megumi Matsutani and Yusuke Narita},

## docs/index.rst and obp/README.md

2.   author={Saito, Yuta, Shunsuke Aihara, Megumi Matsutani, Yusuke Narita},

##  arxiv

3. author={Yuta Saito and Shunsuke Aihara and Megumi Matsutani and Yusuke Narita},

## other possible options

4. author={Yuta Saito, Shunsuke Aihara, Megumi Matsutani, and Yusuke Narita},
5. author={Yuta Saito, Shunsuke Aihara, Megumi Matsutani, Yusuke Narita},

## Question

Which one would be better? (I’ll fix them along with other typos)

**Comment by usaito** [comment]
@fullflu 
`author={Saito, Yuta and Aihara, Shunsuke and Matsutani, Megumi and Narita, Yusuke},`
is correct, thanks!
