### ISSUE TITLE
Any specific code formatter?

### ISSUE THREAD

**Issue by nmasahiro** [st-tech/zr-obp#32]
Hi!
I've found some code implementations that could be improved and I'd like to create a PR.
Regarding the question related to that, is there any specification of code formatter (e.g., [black](https://github.com/psf/black))?
If you can tell us, I will create a PR that matches it.

**Comment by nmasahiro** [comment]
And I think it is desirable to prepare `Contribution Guidelines` if possible.

**Comment by usaito** [comment]
@nmasahiro Yeah, Code is formatted with black, and Coding style is checked with flake8.

**Comment by nmasahiro** [comment]
When I used black and flake8 in my environment, I got a lot of differences from the current code implementation. Do you have any specific settings for these tools?
