### ISSUE TITLE
RegressionModel should use bandit_feedback_test in the quickstart notebook for the synthetic data

### ISSUE THREAD

**Issue by Kurorororo** [st-tech/zr-obp#53]
Since `regression_model` should predict reward values for test data, `regression_model.fit_predict` should take `bandit_feedback_test` instead of `bandit_feedback_train`, which is the training data for the evaluation policy. The current notebook does not raise errors because the sizes of `bandit_feedback_train` and `bandit_feedback_test` are the same.

https://github.com/st-tech/zr-obp/blob/9475cc11c335a15050295c2be184fe0ccc66c45d/examples/quickstart/synthetic.ipynb#L305-L311

The example script correctly uses `bandit_feedback_test` for `regression_model.fit_predict`.

https://github.com/st-tech/zr-obp/blob/9475cc11c335a15050295c2be184fe0ccc66c45d/examples/synthetic/evaluate_off_policy_estimators.py#L166-L172

**Comment by usaito** [comment]
@Kurorororo 
Thanks! You are right. I am now editing the examples with synthetic bandit data for some other reasons and will address this issue later by myself.

**Comment by Kurorororo** [comment]
@usaito I see. I have mistakenly created a PR, so I closed it.

**Comment by usaito** [comment]
@Kurorororo No problem at all!
