### ISSUE TITLE
Parameter eval_size in MultiClassToBanditReduction.obtain_batch_bandit_feedback exists only in the docstring

### ISSUE THREAD

**Issue by Kurorororo** [st-tech/zr-obp#54]
Although the docstring of `MultiClassToBanditReduction.obtain_batch_bandit_feedback` describes parameter `eval_size`, it does not exists. I guess that the docstring should be modified.

https://github.com/st-tech/zr-obp/blob/9475cc11c335a15050295c2be184fe0ccc66c45d/obp/dataset/multiclass.py#L208-L223

**Comment by usaito** [comment]
@Kurorororo 

Thanks! You are right. Can you fix this issue and make a corresponding PR later?
