### ISSUE TITLE
alpha_ and lambda_ are not necessary for contextual linear bandit algorithms

### ISSUE THREAD

**Issue by Kurorororo** [st-tech/zr-obp#66]
Currently, contextual linear and logistic bandit algorithms share the same superclass `BaseContextualPolicy`.
The constructor of `BaseContextualPolicy` has alpha_ and lambda_ as arguments:

https://github.com/st-tech/zr-obp/blob/c9ad20cc89db55c85e1a502e923e9c41ab1635f2/obp/policy/base.py#L93-L129

These arguments are used to initialize `self.alpha_list` and `self.lambda_list`, which are used by `LogisticEpsilonGreedy`, `LogisticTS`, and `LogisticUCB` but not used by `LinearEpsilonGreedy`, `LinTS`, and `LinUCB`.
I suggest moving `alpha_`, `lambda_`,  `self.alpha_list`, and `self.lambda_list` to another class, `BaseLogisticPolicy` for example, and making logistic policies inherit this new class.

**Comment by usaito** [comment]
@Kurorororo Can you fix this issue by yourself after finishing https://github.com/st-tech/zr-obp/pull/78 ?

**Comment by Kurorororo** [comment]
Sure!
