### ISSUE TITLE
what's the meaning of position in OPE?

### ISSUE THREAD

**Issue by LXYTSOS** [st-tech/zr-obp#85]
position: array-like, shape (n_rounds,), default=None
            Positions of each round in the given logged bandit feedback.

I don't quite understand the meaning of 'position' mentioned here, what does "the positions of each round" means?

**Comment by usaito** [comment]
@LXYTSOS 

`position` is the argument to handle the position effect of the Open Bandit Dataset (our public dataset)
As you can see in the [recommendation interface](https://github.com/st-tech/zr-obp/blob/master/images/recommended_fashion_items.png) where we collected the data, there are three positions (left, center, and right). Therefore, we can specify the position at which the item was recommended to the estimators when we use the Open Bandit Dataset.

If you are using synthetic data or multi-classificaiton data, you don't need to care about `position`. It's default value is `None` and this leads to the standard OPE with no positional effect.
