### ISSUE TITLE
Can I use this tool in RL(MDP) environments besides the bandit situation?

### ISSUE THREAD

**Issue by LXYTSOS** [st-tech/zr-obp#86]
Can I use this tool in RL(MDP) environments besides the bandit situation?

**Comment by usaito** [comment]
@LXYTSOS 

No, at this moment. The package now focuses on the contextual bandit setting. 
We may implement tools for MDP later but we will prioritize the implementations of methods to handle combinatorial actions and continuous actions because they are much more practical.
