### ISSUE TITLE
The type check frustrate the policy value calculation

### ISSUE THREAD

**Issue by fang2hou** [st-tech/zr-obp#87]
Thanks for your great work on OBP, I am trying to learn the basics of OBP with the notebook ([online.ipynb](https://github.com/st-tech/zr-obp/blob/master/examples/quickstart/online.ipynb)).

In the section `(3)  Evaluation of OPE`, I tried to use `calc_ground_truth_policy_value` for calculating the policy value but there is a type check.
https://github.com/st-tech/zr-obp/blob/07e545e1e361c1db1e0ffb80007d83e002fc1403/obp/dataset/synthetic.py#L242

I use the following code to check the dtype of actions are `int64`.

```python
epsilon_greedy.select_action().dtype # dtype('int64')
```

I commented out the type check and recompile the library, it works temporarily.

Python: `3.9.2`
numpy: `1.20.2`
OS: `Window 10 x64`

**Comment by fang2hou** [comment]
Same problem in 
https://github.com/st-tech/zr-obp/blob/2591b0268ae28c89493ee07d642ae8a910fea5cc/obp/utils.py#L176

**Comment by Kurorororo** [comment]
I created #89 to fix this issue.

**Comment by usaito** [comment]
@fang2hou @Kurorororo Thank you both!
